name: coo_extensions
description: "coo(l) extensions! A set of commonly used Dart/Flutter extension to ease development."
version: 0.0.1
homepage: https://github.com/coodoo-io/coo_extensions

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
